app:
  database:
    name:
      cap
    username:
      postgres
    password:
      postgres

spring:
  datasource:
    url:
      jdbc:postgresql://127.0.0.1:5432/cap
    username:
      postgres
    password:
      postgres

server:
  port: 8888